[2024-07-05T12:26:26.457+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-07-05T12:26:26.481+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bashscript.bash_task_execute_script manual__2024-07-05T12:26:25.289263+00:00 [queued]>
[2024-07-05T12:26:26.490+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bashscript.bash_task_execute_script manual__2024-07-05T12:26:25.289263+00:00 [queued]>
[2024-07-05T12:26:26.491+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-07-05T12:26:26.505+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): bash_task_execute_script> on 2024-07-05 12:26:25.289263+00:00
[2024-07-05T12:26:26.510+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=70) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-07-05T12:26:26.511+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-07-05T12:26:26.511+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'bashscript', 'bash_task_execute_script', 'manual__2024-07-05T12:26:25.289263+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/dag.py', '--cfg-path', '/tmp/tmpd9ejdxj9']
[2024-07-05T12:26:26.512+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask bash_task_execute_script
[2024-07-05T12:26:26.558+0000] {task_command.py:426} INFO - Running <TaskInstance: bashscript.bash_task_execute_script manual__2024-07-05T12:26:25.289263+00:00 [running]> on host e625dd0edc8e
[2024-07-05T12:26:26.609+0000] {abstractoperator.py:725} ERROR - Exception rendering Jinja template for task 'bash_task_execute_script', field 'bash_command'. Template: '../config.sh'
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 197, in get_source
    pieces = split_template_path(template)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 36, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../config.sh
[2024-07-05T12:26:26.611+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2479, in _run_raw_task
    self._execute_task_with_callbacks(context, test_mode, session=session)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 2633, in _execute_task_with_callbacks
    task_orig = self.render_templates(context=context, jinja_env=jinja_env)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3094, in render_templates
    original_task.render_template_fields(context, jinja_env)
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 1337, in render_template_fields
    self._do_render_template_fields(self, self.template_fields, context, jinja_env, set())
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/abstractoperator.py", line 717, in _do_render_template_fields
    rendered_content = self.render_template(
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/template/templater.py", line 166, in render_template
    template = jinja_env.get_template(value)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 1013, in get_template
    return self._load_template(name, globals)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/environment.py", line 972, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 126, in load
    source, filename, uptodate = self.get_source(environment, name)
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 197, in get_source
    pieces = split_template_path(template)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/jinja2/loaders.py", line 36, in split_template_path
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: ../config.sh
[2024-07-05T12:26:26.619+0000] {taskinstance.py:1206} INFO - Marking task as FAILED. dag_id=bashscript, task_id=bash_task_execute_script, run_id=manual__2024-07-05T12:26:25.289263+00:00, execution_date=20240705T122625, start_date=20240705T122626, end_date=20240705T122626
[2024-07-05T12:26:26.635+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 5 for task bash_task_execute_script (../config.sh; 71)
[2024-07-05T12:26:26.644+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2024-07-05T12:26:26.661+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-05T12:26:26.664+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
